classdef AttackType
    properties (Constant)
        DIRECT_DGSM_DELTA = "DIRECT_DGSM_DELTA"
        IMPLICIT_IDGSM_DELTA = "IMPLICIT_IDGSM_DELTA"
        IMPLICIT_IDGSM_DELTA_POSITIVE = "IMPLICIT_IDGSM_DELTA_POSITIVE"  % deltaを大きくする
        IMPLICIT_IDGSM_DELTA_NEGATIVE = "IMPLICIT_IDGSM_DELTA_NEGATIVE"  % deltaを小さくする
    end
end

